# Use the official Node.js image as the base image
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files to the working directory
COPY . .

# Expose port 8080 to the outside world
EXPOSE 8080

# Start the development server with hot reloading
CMD ["yarn", "serve", "--public",  "http://localhost"]
